apiVersion: v1
kind: ConfigMap
metadata:
  name: common-tracing-store
  namespace: prod
data:
  TRACING_STORE_DB_HOST_RW: "tracing-store-prod.cluster-c72y6ow0q54b.eu-south-1.rds.amazonaws.com"
  TRACING_STORE_DB_HOST_RO: "tracing-store-prod.cluster-ro-c72y6ow0q54b.eu-south-1.rds.amazonaws.com"
  TRACING_STORE_DB_NAME: "tracing_store"
  TRACING_STORE_DB_SCHEMA_TRACING: "prod_tracing"
  TRACING_STORE_DB_SCHEMA_TRACES: "prod_traces"
  TRACING_STORE_DB_PORT: "5432"
  TRACING_STORE_DB_USE_SSL: "true"
