apiVersion: v1
kind: ConfigMap
metadata:
  name: common-flyway-traces-schema
  namespace: qa
data:
  V1__Traces_Schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS ${NAMESPACE}_traces;

    GRANT USAGE ON SCHEMA ${NAMESPACE}_traces to 
      tracing_enriched_data_handler_user,
      tracing_readonly_user;

    CREATE TABLE "${NAMESPACE}_traces".traces (
      id UUID PRIMARY KEY,
      tracing_id UUID,
      submitter_id UUID,
      date TIMESTAMP NOT NULL,
      purpose_id UUID,
      purpose_name VARCHAR(255),
      status INTEGER,
      requests_count INTEGER,
      eservice_id UUID,
      consumer_id UUID,
      consumer_origin VARCHAR(255),
      consumer_name VARCHAR(255),
      consumer_external_id UUID,
      producer_id UUID,
      producer_name VARCHAR(255),
      producer_origin VARCHAR(255),
      producer_external_id UUID,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    GRANT SELECT, INSERT, DELETE ON TABLE "${NAMESPACE}_traces".traces TO tracing_enriched_data_handler_user;
    GRANT SELECT ON TABLE  "${NAMESPACE}_traces".traces TO tracing_readonly_user;

  V1.0.1__Traces_Schema.sql: |-
    ALTER TABLE "${NAMESPACE}_traces".traces
      ALTER COLUMN created_at TYPE TIMESTAMPTZ,
      ALTER COLUMN consumer_external_id TYPE VARCHAR(255),
      ALTER COLUMN producer_external_id TYPE VARCHAR(255);

  V1.0.2__Token_UUID.sql: |-
    ALTER TABLE "${NAMESPACE}_traces".traces
      ADD COLUMN token_id UUID;
