name: "tracing-be-enriched-data-handler"

serviceAccount:
  roleArn: "arn:aws:iam::590183909663:role/tracing-be-enriched-data-handler-dev"

service:
  create: false

configmap:
  DB_SCHEMA_NAME: "tracing"
  APPLICATION_NAME: "tracing-enriched-data-handler"
  SQS_ENRICHED_UPLOAD_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/590183909663/tracing-enriched-upload-dev" #TOCHECK NAMING
  SQS_ENRICHER_STATE_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/590183909663/tracing-enricher-state-dev" #TOCHECK NAMING
  S3_ENRICHED_BUCKET_NAME: "tracing-enriched-files-dev"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "10"

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-redshift-tracing-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "tracing"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-redshift.DB_HOST"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_USE_SSL: "common-redshift.DB_USE_SSL"
    DB_SCHEMA_NAME: "common-redshift.DB_TRACING_SCHEMA"
  envFromSecrets:
    DB_USERNAME: "redshift-tracing-enriched-data-handler-user.username"
    DB_PASSWORD: "redshift-tracing-enriched-data-handler-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"
