name: "tracing-be-enriched-data-handler"

roleArn: "arn:aws:iam::590183909663:role/tracing-be-enriched-data-handler-dev"

service:
  create: false

configmap:
  DB_SCHEMA_NAME: "dev_traces"
  APPLICATION_NAME: "tracing-enriched-data-handler"
  SQS_ENRICHED_UPLOAD_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/590183909663/tracing-enriched-upload-dev" #TOCHECK NAMING
  SQS_ENRICHER_STATE_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/590183909663/tracing-enricher-state-dev" #TOCHECK NAMING
  S3_ENRICHED_BUCKET_NAME: "tracing-enriched-files-dev"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "10"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-traces-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_DEFAULT_SCHEMA: "dev_flyway"
      FLYWAY_SCHEMAS: "dev_flyway,dev_traces"
    envFromConfigmaps:
      POSTGRES_HOST: "common-tracing-store.DB_HOST_RW"
      POSTGRES_PORT: "common-tracing-store.DB_PORT"
      POSTGRES_DB: "common-tracing-store.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "tracing-store-flyway-user.username"
      FLYWAY_PASSWORD: "tracing-store-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-tracing-store.DB_HOST"
    DB_NAME: "common-tracing-store.DB_NAME"
    DB_PORT: "common-tracing-store.DB_PORT"
  envFromSecrets:
    DB_USERNAME: "tracing-store-enriched-data-handler-user.username"
    DB_PASSWORD: "tracing-store-enriched-data-handler-user.password"
