namespace: "uat"
techStack: "nodejs"

deployment:
  replicas: 1
  env:
    LOG_LEVEL: "info"
  image:
    repositoryPrefix: "211125526167.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "2"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
