name: "tracing-be-processing"

serviceAccount:
  roleArn: "arn:aws:iam::537124933279:role/tracing-be-processing-qa"

service:
  create: false

configmap:
  DB_SCHEMA_NAME: "qa_tracing"
  APPLICATION_NAME: "tracing-processing"
  SQS_TRACING_UPLOAD_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/537124933279/tracing-upload-qa"
  SQS_PROCESSING_ERROR_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/537124933279/tracing-processing-error-qa"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "10"
  S3_BUCKET_NAME: "tracing-files-qa"
  S3_ENRICHED_BUCKET_NAME: "tracing-enriched-files-qa"
  BATCH_SIZE: 500

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-tracing-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "qa"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_SCHEMAS: "qa_tracing"
    envFromConfigmaps:
      POSTGRES_HOST: "common-tracing-store.DB_HOST_RW"
      POSTGRES_PORT: "common-tracing-store.DB_PORT"
      POSTGRES_DB: "common-tracing-store.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "tracing-store-flyway-user.username"
      FLYWAY_PASSWORD: "tracing-store-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-tracing-store.DB_HOST_RO"
    DB_NAME: "common-tracing-store.DB_NAME"
    DB_PORT: "common-tracing-store.DB_PORT"
    DB_USE_SSL: "common-tracing-store.DB_USE_SSL"
  envFromSecrets:
    DB_USERNAME: "tracing-store-processing-user.username"
    DB_PASSWORD: "tracing-store-processing-user.password"
