name: "tracing-be-state-updater"

serviceAccount:
  roleArn: "arn:aws:iam::537124933279:role/tracing-be-state-updater-qa"

service:
  create: false

configmap:
  APPLICATION_NAME: "tracing-state-updater"
  SQS_ENDPOINT_PROCESSING_ERROR_QUEUE: "arn:aws:sqs:eu-south-1:537124933279:tracing-processing-error-qa"
  SQS_ENDPOINT_ENRICHER_STATE_QUEUE: "arn:aws:sqs:eu-south-1:537124933279:tracing-enricher-state-qa"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "3"
  API_OPERATIONS_BASEURL: "http://tracing-be-operations.qa:8080"
