apiVersion: v1
kind: ConfigMap
metadata:
  name: common-flyway-traces-schema
  namespace: dev
data:
  V1__Traces_Schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS traces;

    GRANT USAGE ON SCHEMA traces TO
      tracing_be_enriched_data_handler_${NAMESPACE};

    GRANT USAGE ON SCHEMA traces TO GROUP
      readonly_group;

    GRANT CREATE, ALTER, DROP ON SCHEMA traces TO 
      tracing_be_enriched_data_handler_${NAMESPACE};

    CREATE TABLE IF NOT EXISTS traces.traces (
      id UUID PRIMARY KEY,
      tracing_id UUID,
      submitter_id UUID,
      date TIMESTAMP NOT NULL,
      purpose_id UUID,
      purpose_name VARCHAR(255),
      status INTEGER,
      requests_count INTEGER,
      eservice_id UUID,
      consumer_id UUID,
      consumer_origin VARCHAR(255),
      consumer_name VARCHAR(255),
      consumer_external_id UUID,
      producer_id UUID,
      producer_name VARCHAR(255),
      producer_origin VARCHAR(255),
      producer_external_id UUID,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE traces.traces TO
      tracing_be_enriched_data_handler_${NAMESPACE};

  V1.1.0__Token_UUID.sql: |-
    ALTER TABLE traces.traces
      ADD COLUMN token UUID;

  V1.1.1__Token_UUID_Rename.sql: |-
    ALTER TABLE traces.traces
      RENAME COLUMN token TO token_id;
