apiVersion: v1
kind: ConfigMap
metadata:
  name: common-flyway-redshift-tracing-schema
  namespace: dev-analytics
data:
  V1__Tracing_Schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS tracing;

    GRANT USAGE ON SCHEMA tracing TO
      tracing_be_enriched_data_handler_${NAMESPACE};

    GRANT USAGE ON SCHEMA tracing TO GROUP
      readonly_group;

    GRANT CREATE, ALTER, DROP ON SCHEMA tracing TO 
      tracing_be_enriched_data_handler_${NAMESPACE};

    CREATE TABLE IF NOT EXISTS tracing.traces (
      id VARCHAR(36) PRIMARY KEY,
      tracing_id VARCHAR(36),
      submitter_id VARCHAR(36),
      date TIMESTAMP NOT NULL,
      purpose_id VARCHAR(36),
      token_id VARCHAR(36),
      status INTEGER,
      requests_count INTEGER,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tracing.traces TO
      tracing_be_enriched_data_handler_${NAMESPACE};
