apiVersion: v1
kind: ConfigMap
metadata:
  name: common-tracing-store
  namespace: dev
data:
  TRACING_STORE_DB_HOST_RW: "tracing-store-dev.cluster-c5qkocuwywyg.eu-south-1.rds.amazonaws.com"
  TRACING_STORE_DB_HOST_RO: "tracing-store-dev.cluster-ro-c5qkocuwywyg.eu-south-1.rds.amazonaws.com"
  TRACING_STORE_DB_NAME: "tracing_store"
  TRACING_STORE_DB_SCHEMA_TRACING: "dev_tracing"
  TRACING_STORE_DB_SCHEMA_TRACES: "dev_traces"
  TRACING_STORE_DB_PORT: "5432"
  TRACING_STORE_DB_USE_SSL: "true"
