name: "tracing-be-api"

serviceAccount:
  roleArn: "arn:aws:iam::590183909663:role/tracing-be-api-dev"

service:
  create: true
  portName: http
  containerPort: 8080
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:590183909663:targetgroup/dev-tracing-api/9ee153fb0a27a366"

configmap:
  ACCEPTED_AUDIENCES: "http://localhost:4001" #TOCHECK
  APPLICATION_NAME: "tracing-api"
  API_OPERATIONS_BASEURL: "http://tracing-be-operations.dev:8080"
  S3_BUCKET_NAME: "tracing-files-dev"
  STORAGE_PATH_NAME: "/tmp"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8080
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
  livenessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
