name: "tracing-be-state-updater"

serviceAccount:
  roleArn: "arn:aws:iam::637423185147:role/tracing-be-state-updater-uat"

service:
  create: false

configmap:
  APPLICATION_NAME: "tracing-state-updater"
  SQS_ENDPOINT_PROCESSING_ERROR_QUEUE: "https://sqs.eu-south-1.amazonaws.com/637423185147/tracing-processing-error-uat"
  SQS_ENDPOINT_ENRICHER_STATE_QUEUE: "https://sqs.eu-south-1.amazonaws.com/637423185147/tracing-enricher-state-uat"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "3"
  API_OPERATIONS_BASEURL: "http://tracing-be-operations.uat:8080"
