TRACING_API_IMAGE_VERSION="1.x-latest"
TRACING_OPERATIONS_IMAGE_VERSION="1.x-latest"
TRACING_PROCESSING_IMAGE_VERSION="1.x-latest"
TRACING_ENRICHED_DATA_HANDLER_IMAGE_VERSION="1.x-latest"
TRACING_STATE_UPDATER_IMAGE_VERSION="1.x-latest"

JOB_TRACING_CLEANUP_IMAGE_VERSION="1.x-latest"
JOB_TRACING_MISSING_DATA_CHECKER_IMAGE_VERSION="1.x-latest"

# Non usare in dev
#TRACING_API_IMAGE_DIGEST=""
#TRACING_OPERATIONS_IMAGE_DIGEST=""
#TRACING_PROCESSING_IMAGE_DIGEST=""
#TRACING_ENRICHED_DATA_HANDLER_IMAGE_DIGEST=""
#TRACING_STATE_UPDATER_IMAGE_DIGEST=""

#JOB_TRACING_CLEANUP_IMAGE_DIGEST=""
#JOB_TRACING_MISSING_DATA_CHECKER_IMAGE_DIGEST=""