namespace: "dev"

image:
  repositoryPrefix: "590183909663.dkr.ecr.eu-south-1.amazonaws.com"
  imagePullPolicy: Always
  tag: $IMAGE_TAG_PLACEHOLDER
  digest: $IMAGE_DIGEST_PLACEHOLDER

job:
  env:
    LOG_LEVEL: "info"

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
