namespace: "dev"
techStack: "nodejs"

deployment:
  replicas: 1
  env:
    LOG_LEVEL: "info"
  image:
    repositoryPrefix: "211125526167.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

autoscaling:
  keda:
    create: true
    minReplicaCount: 0
    maxReplicaCount: 1
    triggers:
    - type: cron
      metadata:
        timezone: Europe/Rome
        start: 0 8 * * 1-5
        end: 0 20 * * 1-5
        desiredReplicas: "1" # must be a string
